name: ci backend

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  workflow_dispatch:

jobs:
  basic-branch-protection:
    name: basic branch protection
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.X

      - name: build
        run: dotnet build
        working-directory: backend

      - name: test
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: backend