name: ci frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  workflow_dispatch:

jobs:
  basic-branch-protection:
    name: basic branch protection
    runs-on: ubuntu-latest

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: build
        run: |
          npm i
          npm run build
        working-directory: frontend